// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace InterfaceML.Model
{
    public class ModelInput
    {
        [ColumnName("tweet"), LoadColumn(0)]
        public string Tweet { get; set; }


        [ColumnName("desinf"), LoadColumn(1)]
        public string Desinf { get; set; }


        [ColumnName("replies_count"), LoadColumn(2)]
        public float Replies_count { get; set; }


        [ColumnName("retweets_count"), LoadColumn(3)]
        public float Retweets_count { get; set; }


        [ColumnName("likes_count"), LoadColumn(4)]
        public float Likes_count { get; set; }


    }
}
