// This file was auto-generated by ML.NET Model Builder. 

using System;
using InterfaceML.Model;

namespace InterfaceML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Tweet = @"- A Hidroxicloroquina cada vez mais demonstra sua eficÃ¡cia em portadores do COVID-19.- Tenho recebido relatos de todo o Brasil nesse sentido.- Preservar vidas e empregos.-  https://youtu.be/vYLIRzhJIoYÂ  pic.twitter.com/YdP4h3FsD1",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Desinf with predicted Desinf from sample data...\n\n");
            Console.WriteLine($"Tweet: {sampleData.Tweet}");
            Console.WriteLine($"\n\nPredicted Desinf value {predictionResult.Prediction} \nPredicted Desinf scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
